### ISSUE TITLE
Add composer require command

### ISSUE THREAD

**Issue by prolic** [prooph/micro-cli#2]
Description can be taken from the issue here https://github.com/prooph/micro/issues/21, except this is `composer require` and not `composer install/update`.

**Comment by prolic** [comment]
@oqq maybe again? ;)

**Comment by oqq** [comment]
yep assign me :)

**Comment by prolic** [comment]
@oqq still working on this?

**Comment by oqq** [comment]
not yet.. could add some work on weekend, but not earlier.
fine?

**Comment by prolic** [comment]
Ok

Am 02.03.2017 01:36 schrieb "Eric Braun" <notifications@github.com>:

not yet.. could add some work on weekend, but not earlier.
fine?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/prooph/micro-cli/issues/2#issuecomment-283411955>, or mute
the thread
